### PR TITLE
Removed ActionMailer dependency

### PR DESCRIPTION
**Pull request by MarkusHarmsen**
Hey everybody,

just like my previous pull request in 2014 (#73), I removed a dependency to ActionMailer which is not needed.

### CODE REVIEW

**Comment by tagliala** [comment]
Apparently this doesn't work with jruby-19

**Comment by tagliala** [comment]
Also refers to #127

**Comment by MarkusHarmsen** [comment]
Is that really a problem arise from my commit? From the error log it appears that the might be a connection problem with jruby (but I'm not sure). Can you, as the repo owner, request a re-check?

**Comment by tagliala** [comment]
Just restarted build on master branch and your PR

tests are still failing:
```
  1) Failure:
TranslateRoutesTest#test_action_controller_test_case_reads_default_urls [/home/travis/build/enriclluelles/route_translator/test/routing_test.rb:612]:
Failed assertion, no message given.
  2) Failure:
TranslateRoutesTest#test_action_mailer_test_case_reads_default_urls [/home/travis/build/enriclluelles/route_translator/test/routing_test.rb:612]:
Failed assertion, no message given.
  3) Failure:
TranslateRoutesTest#test_action_view_test_case_reads_default_urls [/home/travis/build/enriclluelles/route_translator/test/routing_test.rb:612]:
Failed assertion, no message given.
```

PR: https://travis-ci.org/enriclluelles/route_translator/builds/106943522
master: https://travis-ci.org/enriclluelles/route_translator/builds/105653592

**Comment by tagliala** [comment]
@MarkusHarmsen could you please give a try to this branch?

https://github.com/enriclluelles/route_translator/tree/change-test-case-helpers-loading

**Comment by MarkusHarmsen** [comment]
Works perfectly!

**Comment by tagliala** [comment]
I will release a new version in a short while

**Comment by tagliala** [comment]
@MarkusHarmsen v4.2.4 released

**Pull request closed without merging**
