### PR TITLE
Add section explaining how to generate translated URLs

### LINKED ISSUE #103: No route matches, using url_for to change locale
Example, language selector in the footer: 

Lets say my current url is: `/en/pages/contact`,
and i need a link to `/fr/pages/contact`. (Same page, different locale)

I've tried using `url_for` without success:

```
<% I18n.available_locales.each do |language| %>
  <%= link_to(language, url_for(params.merge(locale: language))%>
<% end %>
```

Error: `No route matches {:action=>"show", :controller=>"pages", :locale=>:fr, :page=>"contact"}`

My route
```
localized do
    get '/pages/:page' => 'pages#show', :as => 'pages'
end
```

PS:
I don't really want a custom helper that is replacing strings,
or route to an action, setting the locale and redirecting `:back`

### PR DESCRIPTION
**Pull request by pkuczynski**
Fixes #103 and #96

### CODE REVIEW

**Comment by tagliala** [comment]
This is not always true

Let's say we use [globalize](https://github.com/globalize/globalize), [friendlyid](https://github.com/norman/friendly_id) with localized slugs

routes.rb
```rb
localized do
  get '/*id', to: 'pages#show', as: :page, constraints: { id: /[^\.\?]*/ }
end
```

page.rb
```rb
class Page < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: [:slugged, :globalize]
end
```

Create page
```rb
[1] pry(main)> I18n.locale
=> :it
[2] pry(main)> page = Page.create title: 'italian-title'
[3] pry(main)> I18n.with_locale(:en) { page.update_attributes slug: 'english-title', title: 'english-title' }
```

show.slim
```slim
dl
  - for locale in I18n.available_locales
    dt= locale
    dd= url_for(locale: locale, only_path: true)
```

Expected result:
```
it /it/italian-title
en /en/english-title
```

Actual Result:
```
it /?id=italian-title&locale=it
en /?id=italian-title&locale=en
```

**Comment by pkuczynski** [comment]
So I must admit I have not worked with either `globalize` or `friendlyid, however what I can notice is that in my case I had following settings applied:

```ruby
RouteTranslator.config do |config|
  # Set this options to true to force the locale to be added to all generated route paths, even for the default locale. Defaults to false.
  config.force_locale = false

  # Set this options to true to force the locale to be hidden on generated route paths. Defaults to false.
  config.hide_locale = true
end
```

Maybe that's making a difference in your case? Can you try it out?

**Comment by pochocosta** [comment]
How is the correct form to get the expected result as you said using friendly_id?
```
it -> /it/italian-title

en -> /en/english-title
```

**Comment by pkuczynski** [comment]
As I have never used `friendly_id`, I simply don't know, sorry :(

**Comment by tagliala** [comment]
@pochocosta yes

**Comment by tagliala** [comment]
but there are some other issues, maybe I used a complex example.

The url_for is not going to work, afaik

If you can help me you will make me very happy! I'm using a complex custom solution to deal with this

**Comment by pkuczynski** [comment]
@tagliala I can only tell you that url_for works in my super simple application which does not use `friendly_id` gem. Maybe you should ask those guys for an answer? Or prepare a mock of your application so I can play around with it and see if I can help...

**Comment by pochocosta** [comment]
@tagliala show us your complex custom solution, to see if we can help

**Comment by tagliala** [comment]
@pochocosta thanks for your willing to help but I'm sorry, I don't think I can do it

Btw I should be able to upload a simple application that shows some issues with this gem

**Comment by pkuczynski** [comment]
@tagliala thats exactly what I mean. Create a simple app showing the issue...

**Comment by tagliala** [comment]
https://github.com/tagliala/route_translator-test/tree/url_for

No friendly id, no globalize

routes.rb
```rb
  localized do
    resources :articles, only: :index
  end
```

articles_controller.rb
```rb
class ArticlesController < ApplicationController
end
```

index.html.erb
```erb
<dl>
  <% for locale in I18n.available_locales %>
    <dt><%= locale %></dt>
    <dl><%= url_for(only_path: true, locale: locale) %></dt>
  <% end %>
</dl>
```

Expected:
```
it /it/articoli
en /articles
```

Got:
```
ActionController::UrlGenerationError in Articles#index
Showing /Users/geremia/dev/route_translator-test/app/views/articles/index.html.erb where line #4 raised:

No route matches {:action=>"index", :controller=>"articles", :locale=>:en}
```

**Comment by tagliala** [comment]
https://github.com/tagliala/route_translator-test/tree/friendly_id_globalize

routes.rb
```rb
  localized do
    resources :articles, only: [:index, :show]
  end
```

articles_controller.rb
```rb
class ArticlesController < ApplicationController
  before_action :set_article, only: :show

  private

  def set_article
    @article = Article.friendly.find(params[:id])
  end
end
```

show.html.erb
```erb
<dl>
  <% for locale in I18n.available_locales %>
    <dt><%= locale %></dt>
    <dl><%= url_for(only_path: true, locale: locale.to_s) %></dt>
  <% end %>
</dl>
```

---

visiting `/articles/english-title`

Expected:
```
en /articles/english-title
it /it/articoli/italian-title
```

Got:
```
en /articles/english-title
it /it/articoli/english-title
```

---

visiting `/it/articoli/italian-title`

Expected:
```
en /articles/english-title
it /it/articoli/italian-title
```

Got:
```
en /articles/italian-title
it /it/articoli/italian-title
```

**Comment by tagliala** [comment]
If you add a note about globalize, I will merge this one

**Comment by tagliala** [comment]
Sorry, I'm going to close this one. I've changed a lot of things

Please feel free to make a new PR against the master branch. If you include a note about globalize, I will merge this for sure

Thanks

**Comment by tagliala** [comment]
Just started this wiki: https://github.com/enriclluelles/route_translator/wiki/Generating-translated-URLs

**Comment by andrespipexz** [comment]
i've a generic answer.
please let me now if it works for you.

in your application_helper.rb


if you have a namespace you can set up in :shop, if not just  `url_for(obj)`
```
def languages(obj)
    content_for(:switch_locale) do
      I18n.available_locales.each do |locale|
        I18n.with_locale(locale) do
          concat(
                content_tag(:li, (link_to locale, url_for([:shop, obj]) ))
          )
        end
      end
  end
end
```

in your views
`- languages @category`

in application.html.(erb/haml.slim) or wherever you want to render the translations.
`=yield(:switch_locale)` 

i know that exist the way yo get the path for the object. if i've time i will post that here.

**Comment by narender2031** [comment]
how to translate the route like 
`get 'test-user-:id', to: "test#show"`

**Comment by tagliala** [comment]
@narender2031 please use the other issue for this question (#190) . I'm going to mark the above comment as OT

**Comment by narender2031** [comment]
Is there any doc or something that can help me in my issue

**Comment by tagliala** [comment]
@narender2031 please find my answer at #190. Please also add any other comment there

**Pull request closed without merging**
