### PR TITLE
Allow disabling i18n fallback to not have unecessary routes

### PR DESCRIPTION
**Pull request by mattvleming**
Original PR: https://github.com/enriclluelles/route_translator/pull/98

@yagnik, since he's so nice, wanted me to open this PR b/c all he did  was clean up the solution I found. 

@enriclluelles @tagliala

### CODE REVIEW

**Comment by yagnik** [comment]
:+1: this is absolutely critical for us.

**Comment by tagliala** [comment]
Thanks, I will take a look later

**Comment by tagliala** [comment]
Could you please add a couple of lines to readme.md explaining this feature: https://github.com/enriclluelles/route_translator#available-configurations , squash commits and push (-f) again?

**Comment by mattvleming** [comment]
@tagliala Alright, I added a cuople of lines to the README.md. Feel free to merge this on your will.

**Comment by tagliala** [comment]
waiting for travis build...

**Comment by yagnik** [comment]
Looks like travis is stuck

**Pull request merged**
