### PR TITLE
RouteTranslator should provide its own config.default_locale(=).

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by tagliala** [comment]
Hi,

failures do not depend on this PR, there is a regression with Rails 5.1.4.

Could you please explain why we need this?

I would also like a commit message with a title shorter than 50 characters (e.g.: "Provide a default locale configuration option") with one empty line and a description of why you are doing this. Also, as per contributing guidelines, since this is not a fix you should push against the develop branch

**Comment by n-rodriguez** [comment]
Hi!
I use this gem in a Rails engine and the Rails engine doesn't have the same default language than the main Rails app. The main app language is `:en`, the Rails engine language is `:es` and I don't want the locale to appear in the URL for the default language.

**Comment by tagliala** [comment]
Thanks.

I don't know if the rails engine support will be still available in Route Translator 6.

At the moment, I will drop that feature for sure, because I don't want to maintain it and I'm not getting answers on #172 

If I drop that feature, is this PR still useful?

Also:
- this needs documentation
- this needs a failing spec (e.g: engine with its own language, main app with another language, spec failing on the current master branch, spec failing with this PR)

**Comment by n-rodriguez** [comment]
it's a bad new that you stop supporting Rails engines :(. Actually I was very happy to see how easy it was to add translated routes in my app engine.

**Comment by n-rodriguez** [comment]
To explain a little bit the use case : I have a multi domain Rails app :
* admin.foo.com is the main Rails app
* www.foo.es is an engine to serve the spanish version of the website
* www.foo.com is an engine to serve the english version of the website

**Pull request closed without merging**
