### PR TITLE
Add Rails > 6.0 compatibility

### LINKED ISSUE #209: Incompatible with Rails 6.1
### Steps to reproduce

Run bundle with this Gemfile:
```rb
gem 'rails', github: 'rails/rails'
gem 'route_translator'
```

### Expected behavior

Route translator should be compatible with Rails >= 6.1. I am currently using Rails 6.0.2.2 but need to try new ActiveStorage features only available on Rails master (6.1.0-alpha). This is both to improve my app and possibly to submit contributions to the Rails repo.

### Actual behavior

Bundle install fails.

### System configuration
**Rails version**: Rails master (6.1.0-alpha)
**Ruby version**: 2.6.6
**Route Translator version**: 7.1.2

### I18n configuration

```rb
Rails.application.config.i18n.available_locales = [:en, :fr]
```

### Route Translator initializier

Source of: `config/initializers/route_translator.rb`

```rb
RouteTranslator.config do |config|
  config.locale_param_key = :path_locale
end
```

### PR DESCRIPTION
**Pull request by sedubois**
Fixes #209

### CODE REVIEW

**Comment by tagliala** [comment]
Hi, thanks for this PR.

I will open a new `rails-6.1` branch and merge, but I cannot accept < 7.0 on the master branch until we have a Release Candidate, sorry.

Also, Release Candidate appears to be an optimistic choice, because route_translator relies on Rails' internal API and that changed between 6.0.0.rc1 and 6.0.0.rc2, take a look at #195

I will ask you to rebase in a few hours

**Comment by sedubois** [comment]
Thanks @tagliala, understood. Let me know when to rebase.

**Comment by tagliala** [comment]
Hi @sedubois , I've released version 8.0.0 which drops Rails 2.3 support

Please rebase on branch `rails-edge` and feel free to change this PR to push against that branch, I will be happy merge

Also, I've noticed that in order to fix #195 I've switched to another method with the same signature across all compatible rails versions, and this explains why specs are green against rails-edge 😅

Ref: d8a6fba7b4ba8f91299129a4d26b59319880c929

**Comment by sedubois** [comment]
Thanks @tagliala, I've rebased and changed target branch to `rails-edge`.

**Comment by tagliala** [comment]
Merged, thanks. Please report any error you may find

**Comment by sedubois** [comment]
Hi @tagliala, would it be possible to have an alpha release with this gem (similar to what was done with [Globalize](https://github.com/globalize/globalize/pull/755#issuecomment-616231774))?

**Comment by tagliala** [comment]
Is Rails 6.1 around the corner?

**Comment by sedubois** [comment]
This would be helpful to run route translator along with Rails 6.1 alpha, in order to test it and submit new features. Considering that I find Rails alpha already stable enough, I am even weighing whether I might already deploy it in production.

But if that is a problem for some reason I can just directly refer to the branch you created (it mostly just makes for a messier Gemfile.lock).

**Comment by sedubois** [comment]
> Is Rails 6.1 around the corner?

@tagliala yes: https://discuss.rubyonrails.org/t/release-schedules/74595/2

> the 6.1 release is going into beta any moment now. So should have the final in maybe a month or two.

**Comment by tagliala** [comment]
@sedubois I've just released 8.2.0 with Rails 6.1 compatibility, hoping that nothing is going to break between RCs

**Pull request merged**
